namespace coro_cloudbrowser_winrt {

enum FileType { kDirectory, kAudio, kImage, kVideo, kUnknown };

[bindable][default_interface] runtimeclass FileListEntryModel
    : Windows.UI.Xaml.Data.INotifyPropertyChanged {
  String Size;
  String Id;
  String Filename;
  String Thumbnail;
  String Timestamp;
  Windows.UI.Xaml.Visibility ThumbnailVisibility;
  String Icon;
  Windows.UI.Xaml.Visibility IconVisibility;
  FileType Type;
  String Uri;
}
}  // namespace coro_cloudbrowser_winrt
