namespace coro_cloudbrowser_winrt {
[bindable][default_interface] runtimeclass FileListEntryModel
    : Windows.UI.Xaml.Data.INotifyPropertyChanged {
  String Size;
  String Id;
  String Filename;
  String Thumbnail;
  String Timestamp;
  Windows.UI.Xaml.Visibility ThumbnailVisibility;
  String Icon;
  Windows.UI.Xaml.Visibility IconVisibility;
}
}  // namespace coro_cloudbrowser_winrt
