import "CloudProviderAccountModel.idl";
import "FileListEntryModel.idl";

namespace coro_cloudbrowser_winrt {
[bindable][default_interface] runtimeclass FileListPageModel {
  CloudProviderAccountModel Account;
  String Path;
  String ScrollPosition;
  IObservableVector<FileListEntryModel> Items;
}
}  // namespace coro_cloudbrowser_winrt
