import "CloudProviderAccountModel.idl";
import "CloudProviderTypeModel.idl";

namespace coro_cloudbrowser_winrt {
[bindable][default_interface] runtimeclass MainPageModel {
  IObservableVector<CloudProviderAccountModel> Accounts;
  IVector<CloudProviderTypeModel> ProviderTypes;
}
}  // namespace coro_cloudbrowser_winrt
